version: "3.7"

services:
  web:
    image: "webdevops/php-apache-dev:8.1"
    container_name: magento-web
    restart: unless-stopped
    volumes:
      - ../src:/var/www/html
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html
    ports:
      - "80:80"
  db:
    image: mariadb:10.4
    container_name: magento-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: magento-phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: "2048M"

volumes:
  db-data:
