version: "3.8"

services:
  web:
    build: .
    container_name: magento_web
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
    depends_on:
      - db
      - elasticsearch

  db:
    image: mariadb:10.5
    container_name: magento_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: magento2
      MYSQL_USER: meetanshi
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: magento_elasticsearch
    environment:
      discovery.type: single-node
      network.host: 0.0.0.0
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  db_data:
  es_data:
