version: "3.7"

services:
  web:
    image: "webdevops/php-apache-dev:8.1"
    container_name: magento-web
    restart: unless-stopped
    volumes:
      - ../src:/var/www/html
    environment:
      - WEB_PHP_SOCKET=php-fpm:9000
      - WEB_DOCUMENT_ROOT=/var/www/html/pub
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - db

  php-fpm:
    image: "webdevops/php-apache-dev:8.1"
    container_name: magento-php-fpm
    restart: unless-stopped
    volumes:
      - ../src:/var/www/html

  db:
    image: mariadb:10.4
    container_name: magento-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    ports:
      - "3306:3306" # This line should be exactly like this to expose it on localhost
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: magento-phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: "2048M"

volumes:
  db-data:
